name: Run The Internet Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Set up Chrome Browser
        run: sudo apt-get update sudo apt-get install -y google-chrome-stable

      - name: Set up ChromeDriver
        run: sudo apt-get update sudo apt-get install -y chromium-chromedriver

      - name: Install Maven dependencies
        run: mvn install --no-transfer-progress --batch-mode

      - name: Run Tests
        run: mvn test --no-transfer-progress --batch-mode